// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIN7BWGymJ6F41pQCeHI8Jh_9VdRu25qw',
    appId: '1:63956203212:web:8e0845abe261e4c80a3469',
    messagingSenderId: '63956203212',
    projectId: 'mydiary-22626',
    authDomain: 'mydiary-22626.firebaseapp.com',
    storageBucket: 'mydiary-22626.appspot.com',
    measurementId: 'G-YX0JZFX82W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPLagnt-rAjNBzhQrBCKrZFFV3ZWKpkiw',
    appId: '1:63956203212:android:c1eb28c23f32b5ed0a3469',
    messagingSenderId: '63956203212',
    projectId: 'mydiary-22626',
    storageBucket: 'mydiary-22626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRLT83QmKmgwRVSB7lRvXAK3IGd1G7LSg',
    appId: '1:63956203212:ios:86c9a1bcf8f9793a0a3469',
    messagingSenderId: '63956203212',
    projectId: 'mydiary-22626',
    storageBucket: 'mydiary-22626.appspot.com',
    iosBundleId: 'com.example.myDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRLT83QmKmgwRVSB7lRvXAK3IGd1G7LSg',
    appId: '1:63956203212:ios:ce105bf55ff5f8c00a3469',
    messagingSenderId: '63956203212',
    projectId: 'mydiary-22626',
    storageBucket: 'mydiary-22626.appspot.com',
    iosBundleId: 'com.example.myDiary.RunnerTests',
  );
}
